# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Main CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: |
        pushd './event-management-backend/src'
        dotnet restore
        popd
    - name: Build
      run: |
        pushd './event-management-backend/src'
        dotnet build --no-restore
        popd
    - name: Test
      run: |
        pushd './event-management-backend/src'
        dotnet test --no-build --verbosity normal
        popd
